apiVersion: v2
name: dtrack
sources:
  - https://github.com/KvalitetsIT/dtrack/tree/main/charts
description: A Helm chart for Kubernetes
type: application
version: 0.5.2

dependencies:
  - name: trivy
    version: "0.19.1"
    repository: "https://aquasecurity.github.io/helm-charts"
