{{- if .Values.backend.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "dependencytrack-backend.name" . }}
  labels:
    {{- include "dependencytrack-backend.labels" . | nindent 4 }}
  {{- if .Values.backend.ingress.annotations }}
  annotations:
    {{- toYaml .Values.backend.ingress.annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.backend.ingress.className }}
  ingressClassName: {{ .Values.backend.ingress.className }}
  {{- end }}
  {{- if .Values.backend.ingress.tls }}
  tls:
    {{- toYaml .Values.backend.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.backend.ingress.host | quote }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "dependencytrack-backend.name" . }}
                port:
                  number: 8080
            path: /
            pathType: Prefix
{{- end }}
