{{- if .Values.backend.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dependencytrack.name" . }}
  labels:
    {{- include "dependencytrack-backend.labels" . | nindent 4 }}
{{- end }}
