{{- if .Values.frontend.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "dependencytrack-frontend.name" . }}
  labels:
    {{- include "dependencytrack-frontend.labels" . | nindent 4 }}
  {{- if .Values.frontend.ingress.annotations }}
  annotations:
    {{- toYaml .Values.frontend.ingress.annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.frontend.ingress.className }}
  ingressClassName: {{ .Values.frontend.ingress.className }}
  {{- end }}
  {{- if .Values.frontend.ingress.tls }}
  tls:
    {{- toYaml .Values.frontend.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.frontend.ingress.host | quote }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "dependencytrack-frontend.name" . }}
                port:
                  number: 80
            path: /
            pathType: Prefix
        {{- if .Values.frontend.swagger.enabled }}
          - backend:
              service:
                name: {{ include "dependencytrack-frontend.name" . }}
                port:
                  number: 81
            path: {{ .Values.frontend.swagger.path }}
            pathType: Prefix
        {{- end }}
{{- end }}
