name: Build
on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
      - "LICENSE.md"

jobs:
  tests:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version-file: ./go.mod
          cache-dependency-path: ./go.sum

      - name: Run unit tests
        run: make test

      - name: Check for code
        run: make check

      - name: run integration tests
        run: make integration_test

  bootstrap:
    outputs:
      version: ${{ steps.output_version.outputs.version }}
    needs:
      - tests
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Log in to Docker Hub
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Extract metadata
        id: metadata
        uses: docker/metadata-action@318604b99e75e41977312d83839a89be02ca4893 # v5.9.0
        with:
          images: docker.io/kvalitetsit/dtrack-bootstrap
          tags: |
            type=raw,value={{date 'YYYY-MM-DD-HHmmss' tz='Europe/Copenhagen'}}-{{sha}}

      - name: Build and push image
        id: build_push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          sbom: true
          provenance: true
          file: Dockerfile

      - name: install cosign
        uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad # v4.0.0

      - name: sign image
        run: |
          cosign sign --yes docker.io/kvalitetsit/dtrack-bootstrap@${{ steps.build_push.outputs.digest }}

      - name: verify signature
        run: |
          cosign verify docker.io/kvalitetsit/dtrack-bootstrap@${{ steps.build_push.outputs.digest }} \
             --certificate-identity https://github.com/KvalitetsIT/dtrack/.github/workflows/main.yml@refs/heads/main \
             --certificate-oidc-issuer https://token.actions.githubusercontent.com | jq

      - name: Output version
        id: output_version
        run: |
          echo "version=${{ fromJSON(steps.metadata.outputs.json).labels['org.opencontainers.image.version'] }}" >> $GITHUB_OUTPUT

  helm:
    runs-on: ubuntu-latest
    needs:
      - bootstrap
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
        name: "Setup Helm"
        with:
          version: "v3.17.0"

      - name: Update values.yaml with yq
        run: |-
          yq -i '.bootstrap.image.tag = "${{ needs.bootstrap.outputs.version }}"' charts/values.yaml

      - name: Build Chart
        run: |-
          sed -i "s/^version: .*/version: ${{ needs.bootstrap.outputs.version }}/g" charts/Chart.yaml
          helm package charts

      - name: Configure Git
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "development@kvalitetsit.dk"

      - name: Checkout Helm repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: KvalitetsIT/helm-repo
          token: ${{ secrets.KIT_GITHUB_ACCESS }}
          path: helm-repo

      - name: Update and push Helm repo
        run: |
          mkdir -p helm-repo/dtrack
          cp dependencytrack-*.tgz helm-repo/dtrack/
          cd helm-repo
          helm repo index . --url https://raw.githubusercontent.com/KvalitetsIT/helm-repo/master/
          git add -A
          git commit -m "Adding new dtrack chart"

          echo "Verify changes before pushing:"
          ls -la
          ls -la dtrack
          git status

          git push


